server:
  port: 8081   # HTTP (Tomcat) port
# Spring properties
spring:
  application:
    name: orders
  # kafka configuration provider
  kafka:
    bootstrap-servers: localhost:9092

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ms_orders
    username: root # name similar to the docker compose orders Db
    password: 12345678 # name similar to the docker compose orders Db
  jpa:
    hibernate.ddl-auto: update # create-drop
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true





