server:
  port: 0   # HTTP (Tomcat) port

  # Swagger OpenApi

  servlet:
    context-path: /

# Spring properties
spring:
  application:
    name: order-service
  # kafka configuration provider
  kafka:
    bootstrap-servers: localhost:9092

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ms_orders
    username: root # name similar to the docker compose orders Db
    password: 12345678 # name similar to the docker compose orders Db
  jpa:
    hibernate.ddl-auto: update # create-drop
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

  .instance:
    instance-id=${spring.application.name}:${spring.application.instance_id:${random:value}}

#Actuator
  management:
    endpoints:
      web:
        exposure:
         include: health
      base-path: /actuator/orders
    endpoint:
      health:
        show-details: always
    health:
      circuitbreakers:
        enabled: true

#Resilience4j - Circuit Breaker
resilience4j.circuitbreaker.instances.orders.register-health-indicator: true
resilience4j.circuitbreaker.instances.orders.sliding-window-size: 5
resilience4j.circuitbreaker.instances.orders.sliding-window-type: count_based
resilience4j.circuitbreaker.instances.orders.failure-rate-threshold: 50
resilience4j.circuitbreaker.instances.orders.wait-duration-in-open-state: 10s
resilience4j.circuitbreaker.instances.orders.automatic-transition-from-open-to-half-open-enabled: true
resilience4j.circuitbreaker.instances.orders.permitted-number-of-calls-in-half-open-state: 3
# To access the API Documentation:
# http://localhost:8080/swagger-ui/index.html

# API Documentation in JSON format:
# http://localhost:8080/v3/api-docs

openapi:
  service:
    title: order-service doc #title that you will want to display in the swagger ui
    version: 1.0.0
    url: http://localhost:8080 #api gateway url
springdoc:
  api-docs:
    path: /order-service/v3/api-docs #these urls will used to load the swagger ui of this service by the api gateway
  swagger-ui:
    path: /order-service/swagger-ui.html