server:
  port: 8080   # HTTP (Tomcat) port
# Spring properties
spring:
  application:
    name: orders
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ms_orders
    username: ecommerce # name similar to the docker compose orders Db
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true