# HTTP (Tomcat) port
server:
  port: 0

  # Swagger OpenApi

  servlet:
    context-path: /

# SPRING PROPERTIES
spring:
  application:
    name: customer-service
  # kafka configuration provider
  kafka:
    bootstrap-servers: localhost:9092
  # MongoDB DDBB
  data:
    mongodb:
      #uri: mongodb://localhost:28017/
      #host: localhost
      #port: 28017
      #database: CustomersDDBB
      #username: root
      #password: 1234567891011
      #authentication-database: root

      uri: mongodb://root:1234567891011@localhost:28017/CustomersDDBB?authSource=admin&authMechanism=SCRAM-SHA-1
      #uuid-representation: standard

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  .instance:
    instance-id=${spring.application.name}:${spring.application.instance_id:${random:value}}

# To access the API Documentation:
# http://localhost:8080/swagger-ui/index.html

# API Documentation in JSON format:
# http://localhost:8080/v3/api-docs

openapi:
  service:
    title: customer-service doc #title that you will want to display in the swagger ui
    version: 1.0.0
    url: http://localhost:8080 #api gateway url
springdoc:
  api-docs:
    path: /customer-service/v3/api-docs #these urls will used to load the swagger ui of this service by the api gateway
  swagger-ui:
    path: /customer-service/swagger-ui.html

