# HTTP (Tomcat) port
server:
  port: 0

# SPRING PROPERTIES
spring:
  application:
    name: customers
  # kafka configuration provider
  kafka:
    bootstrap-servers: localhost:9092
  # MongoDB DDBB
  data:
    mongodb:
      #host: db-customers
      #host: localhost
      #port: 28017
      #database: CustomersDDBB
      #authentication-database: CustomersDDBB
      #repositories:
       # enable: true
      #username: root
      #password: 1234567891011
      #password: 12345678
      #uri: mongodb://localhost:28017/
      #uri: mongodb://root:1234567891011@localhost:28017/CustomersDDBB?authMechanism=DEFAULT
      #uri: mongodb://root:1234567891011@localhost:28017/?authMechanism=DEFAULT
      #uri: mongodb://root:1234567891011@localhost:28017/CustomersDDBB
      #uri: mongodb://admin:A123456789@localhost:28017/CustomersDDBB
      #uri: mongodb://root:12345678@localhost:28017/CustomersDB
      uri: mongodb://root:1234567891011@localhost:28017/CustomersDDBB?authSource=admin&authMechanism=SCRAM-SHA-1
      #uri: mongodb://root:12345678@localhost:28017
      #uuid-representation: standard

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  .instance:
    instance-id=${spring.application.name}:${spring.application.instance_id:${random:value}}



