# HTTP (Tomcat) port
server:
  port: 0

# SPRING PROPERTIES
spring:
  application:
    name: customers
  # kafka configuration provider
  kafka:
    bootstrap-servers: localhost:9092
  # MongoDB DDBB
  data:
    mongodb:
      host: db-customers
      port: 27017
      username: root
      password: 12345678
      database: CustomersDB

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  .instance:
    instance-id=${spring.application.name}:${spring.application.instance_id:${random:value}}



