server:
  port: 0   # HTTP (Tomcat) port
# Spring properties
spring:
  application:
    name: Notification
  kafka:
    bootstrap-servers: localhost:9092

# Eureka client
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

  .instance:
    instance-id=${spring.application.name}:${spring.application.instance_id:${random:value}}